import Head from 'next/head'
import Image from 'next/image'
import Error from '../components/Error'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({status,results}) {
  const data = () => {
    return(
      <>
        
        <Results results={results}/>
      </>
    )
  }

  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      
      {status && data()}
      {!status && <Error/>}
      
        
      

    </div>
  )
}

export async function getServerSideProps(context) {
    const genre = context.query.genre;
    console.log(genre);
    const request = await fetch(`https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`)
    .then((response)=> response.json())
    .catch((err)=>console.log(err))

    try{
      return{
        props: {
          status: true,
          results: request.results,
        },
      };
    }
    catch{
      return{
        props: {
          status: false,
          results: {
            
          }
        },
      };
    }
    
}
